name: Publish DCOM Core to Maven Packages
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Configure Maven
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "DCOMCORE", "username": "beachtom", "password": "${{ secrets.MAVEN_TOKEN }}"}]'
      - name: Set Version
        run: mvn versions:set -DnewVersion=${{ github.event.release.name }}
      - name: Publish package
        run: mvn --batch-mode -DskipTests deploy
      - name: Update Repository
        uses: peter-evans/create-pull-request@v5
        with:
          base: main